Remove skylight
1. We aren't actively using it
2. It is causing an error with latest Rails `master` (NoMethodError:
   undefined method `instrument' for
   <ActionView::TemplateRenderer:0x00007f32880c9ab0>) ; see
   https://travis-ci.org/github/davidrunger/david_runger/builds/675537853