Remove invalid options from css-loader config
Even though we are removing an `hmr: true` option, HMR CSS reloading
still seems to work.

I'm not sure what the `convertToAbsoluteUrls` option was supposedly
doing for us, but removing it doesn't have any obvious ill effects.

CSS source maps still seem to work (which is the one option that we were
using before that still seems to be valid).

This change should hopefully fix errors like this that we are seeing
from the css-loader 1.0.1 to 3.0.0 version bump (see
https://github.com/webpack-contrib/css-loader/issues/ 955):

Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties

    at validateOptions (/Users/david/workspace/david_runger/node_modules/schema-utils/src/validateOptions.js:32:11)
    at Object.loader (/Users/david/workspace/david_runger/node_modules/css-loader/dist/index.js:34:28)