Bump vega, vega-embed, and add explicitly and bump vega-lite
vega: 5.33.0 to 6.1.2

vega-embed: 6.29.0 to 7.0.2

vega-lite: (indirect) 5.23.0 to (explicit) 6.1.0

Everything seems to still work.

I'm changing the `tsconfig` `moduleResolution` (docs:
https://www.typescriptlang.org/tsconfig/#moduleResolution ) from `node`
to `bundler` because it avoids this error:

```
Running system command './node_modules/.bin/vue-tsc --noEmit' with ENV vars {} ...
app/javascript/ci_step_results/renderGanttCharts.ts(1,47): error TS2307: Cannot find module 'vega-embed' or its corresponding type declarations.
  There are types at '/home/david/code/david_runger/node_modules/vega-embed/build/embed.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.
'./node_modules/.bin/vue-tsc --noEmit' with ENV vars {} failed (exited with 1, took 18.866).
```